/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Symon Hasan
 */
public class Main extends javax.swing.JFrame {

    boolean creditflag=false,startflag=false;
    Gameconsole ob1=new Gameconsole();
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainUI = new javax.swing.JPanel();
        help = new javax.swing.JButton();
        start = new javax.swing.JButton();
        credit = new javax.swing.JButton();
        scores = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MagicBOX");
        setMaximumSize(new java.awt.Dimension(500, 510));
        setMinimumSize(new java.awt.Dimension(500, 510));
        setPreferredSize(new java.awt.Dimension(500, 510));
        setResizable(false);
        getContentPane().setLayout(null);

        MainUI.setLayout(null);

        help.setBackground(java.awt.SystemColor.controlHighlight);
        help.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        help.setForeground(java.awt.SystemColor.textHighlight);
        help.setText("HELP");
        help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        MainUI.add(help);
        help.setBounds(80, 300, 120, 50);

        start.setBackground(java.awt.SystemColor.controlHighlight);
        start.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        start.setForeground(java.awt.SystemColor.textHighlight);
        start.setText("START");
        start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        MainUI.add(start);
        start.setBounds(80, 180, 120, 50);

        credit.setBackground(java.awt.SystemColor.controlHighlight);
        credit.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        credit.setForeground(java.awt.SystemColor.textHighlight);
        credit.setText("CREDIT");
        credit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditActionPerformed(evt);
            }
        });
        MainUI.add(credit);
        credit.setBounds(270, 360, 120, 50);

        scores.setBackground(java.awt.SystemColor.controlHighlight);
        scores.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        scores.setForeground(java.awt.SystemColor.textHighlight);
        scores.setText("SCORES");
        scores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoresActionPerformed(evt);
            }
        });
        MainUI.add(scores);
        scores.setBounds(270, 240, 120, 50);

        Exit.setBackground(java.awt.SystemColor.controlHighlight);
        Exit.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        Exit.setForeground(java.awt.SystemColor.textHighlight);
        Exit.setText("EXIT");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        MainUI.add(Exit);
        Exit.setBounds(80, 430, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUI.jpg"))); // NOI18N
        MainUI.add(jLabel1);
        jLabel1.setBounds(0, -10, 500, 510);

        getContentPane().add(MainUI);
        MainUI.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditActionPerformed
        creditflag=true;
        if(creditflag)
        {
            Credit ob= new Credit();
            ob.setVisible(true);
            this.setVisible(false);
            creditflag=false;
        }
    }//GEN-LAST:event_creditActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        startflag=true;
        if(startflag)
        {
            if(!ob1.nameflag)
            {
                NameUI ob2=new NameUI();
                ob2.setVisible(true);
                this.setVisible(false);
                ob1.nameflag=true;
            }
            else
            {
            Gameconsole ob= new Gameconsole();
            ob.setVisible(true);
            this.setVisible(false);
            startflag=false;
            }
        }
    }//GEN-LAST:event_startActionPerformed

    private void scoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoresActionPerformed
        ScoreUI sc=new ScoreUI();
        sc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_scoresActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        HelpUI ob=new HelpUI();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_helpActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JPanel MainUI;
    private javax.swing.JButton credit;
    private javax.swing.JButton help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton scores;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
