
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Symon Hasan
 */
public class NameUI extends javax.swing.JFrame {

    /**
     * Creates new form NameUI
     */
    Gameconsole ob=new Gameconsole();
    public NameUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        namebox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NAME");
        setPreferredSize(new java.awt.Dimension(490, 200));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PLEASE ENTER YOUR NAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 10, 360, 50);

        OK.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        OK.setForeground(java.awt.SystemColor.textHighlight);
        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        jPanel1.add(OK);
        OK.setBounds(190, 130, 100, 40);

        namebox.setFont(new java.awt.Font("Slave only dreams to be king", 0, 36)); // NOI18N
        namebox.setForeground(java.awt.SystemColor.textHighlight);
        namebox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(namebox);
        namebox.setBounds(150, 70, 190, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NameUI.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 200));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -60, 550, 350);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        if(namebox.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"You Must Enter A Name !");
        }
        else
        {
            ob.name=namebox.getText();
            Gameconsole ob2=new Gameconsole();
            ob2.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_OKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namebox;
    // End of variables declaration//GEN-END:variables
}
