/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Symon Hasan
 */
public class ScoreUI extends javax.swing.JFrame {

    static String name="",s1="";

    void set()
    {
        namebox1.setText(ScoreUI.name );
        scorebox1.setText(" - " + s1);
    }
    
    public ScoreUI() {
        initComponents();
        namebox1.setText(ScoreUI.name );
        scorebox1.setText(" - " + s1);
        name="";
        s1="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scorebox1 = new javax.swing.JLabel();
        namebox1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCORES");
        setPreferredSize(new java.awt.Dimension(500, 510));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCORES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 30, 180, 90);

        scorebox1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        scorebox1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(scorebox1);
        scorebox1.setBounds(220, 160, 260, 40);

        namebox1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        namebox1.setForeground(new java.awt.Color(102, 204, 255));
        jPanel1.add(namebox1);
        namebox1.setBounds(10, 160, 190, 40);

        Back.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        Back.setForeground(java.awt.SystemColor.textHighlight);
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(180, 340, 110, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NameUI.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, -10, 530, 490);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Main ob=new Main();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel namebox1;
    private javax.swing.JLabel scorebox1;
    // End of variables declaration//GEN-END:variables
}
